# gitea_3_deployment.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config3
data:
  ROOT_URL: http://harmonia-gitea3:3000
  LFS_START_SERVER: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-3-deployment # pod name
  labels:
    app: gitea3 # label備註
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: gitea3
  template:
    metadata:
      labels:
        app: gitea3
    spec:
      nodeName: worker4
      containers: 
        - name: gitea3
          image: gitea/gitea:1.15.5-linux-amd64
          ports:
            - containerPort: 3000
              name: gitea3
          envFrom:
            - configMapRef:
                name: gitea-config3
          volumeMounts:
            - mountPath: /data3
              name: test-volume3
      volumes:
        - name: test-volume3 
          hostPath:
            path: /home/harmonia-gitea 
            type: DirectoryOrCreate

---
kind: Service
apiVersion: v1
metadata:
  name: harmonia-gitea3 # service名稱
spec:
  selector:
    app: gitea3
  ports:
  - name: gitea3-http
    port: 3003
    targetPort: 3000
    # nodePort: 30001
  type: NodePort
