# gitea_2_deployment.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config2
data:
  ROOT_URL: http://harmonia-gitea2:3002
  LFS_START_SERVER: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-2-deployment # pod name
  labels:
    app: gitea2 # label備註
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: gitea2
  template:
    metadata:
      labels:
        app: gitea2
    spec:
      nodeName: worker2
      containers: 
        - name: gitea2
          image: gitea/gitea:1.15.5-linux-amd64
          ports:
            - containerPort: 3002
              name: gitea2
          envFrom:
            - configMapRef:
                name: gitea-config2
          volumeMounts:
            - mountPath: /data2 
              name: test-volume2
      volumes:
        - name: test-volume2 # valume名稱也要不同
          hostPath:
            path: /home/harmonia-gitea
            type: DirectoryOrCreate

---
kind: Service
apiVersion: v1
metadata:
  name: harmonia-gitea2 # service名稱
spec:
  selector:
    app: gitea2
  ports:
  - name: gitea2-http
    port: 3002
    targetPort: 3000
    nodePort: 30002
  type: NodePort
